default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: xxxxx #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devcanvas_development

test:
  <<: *default
  database: devcanvas_test

production:
  <<: *default
  database: devcanvas_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
